// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_fort_RCPPEXPORTS_H_GEN_
#define RCPP_fort_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace fort {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("fort", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("fort", "_fort_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in fort");
            }
        }
    }

    inline arma::vec a1_fn_ip(const arma::vec& theta, const arma::vec& known_params) {
        typedef SEXP(*Ptr_a1_fn_ip)(SEXP,SEXP);
        static Ptr_a1_fn_ip p_a1_fn_ip = NULL;
        if (p_a1_fn_ip == NULL) {
            validateSignature("arma::vec(*a1_fn_ip)(const arma::vec&,const arma::vec&)");
            p_a1_fn_ip = (Ptr_a1_fn_ip)R_GetCCallable("fort", "_fort_a1_fn_ip");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_a1_fn_ip(Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::mat P1_fn_ip(const arma::vec& theta, const arma::vec& known_params) {
        typedef SEXP(*Ptr_P1_fn_ip)(SEXP,SEXP);
        static Ptr_P1_fn_ip p_P1_fn_ip = NULL;
        if (p_P1_fn_ip == NULL) {
            validateSignature("arma::mat(*P1_fn_ip)(const arma::vec&,const arma::vec&)");
            p_P1_fn_ip = (Ptr_P1_fn_ip)R_GetCCallable("fort", "_fort_P1_fn_ip");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_P1_fn_ip(Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::mat H_fn_ip(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_H_fn_ip)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_H_fn_ip p_H_fn_ip = NULL;
        if (p_H_fn_ip == NULL) {
            validateSignature("arma::mat(*H_fn_ip)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_H_fn_ip = (Ptr_H_fn_ip)R_GetCCallable("fort", "_fort_H_fn_ip");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_H_fn_ip(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::mat R_fn_ip(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_R_fn_ip)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_R_fn_ip p_R_fn_ip = NULL;
        if (p_R_fn_ip == NULL) {
            validateSignature("arma::mat(*R_fn_ip)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_R_fn_ip = (Ptr_R_fn_ip)R_GetCCallable("fort", "_fort_R_fn_ip");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_R_fn_ip(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::vec Z_fn_ip(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_Z_fn_ip)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_Z_fn_ip p_Z_fn_ip = NULL;
        if (p_Z_fn_ip == NULL) {
            validateSignature("arma::vec(*Z_fn_ip)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_Z_fn_ip = (Ptr_Z_fn_ip)R_GetCCallable("fort", "_fort_Z_fn_ip");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Z_fn_ip(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::mat Z_gn_ip(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_Z_gn_ip)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_Z_gn_ip p_Z_gn_ip = NULL;
        if (p_Z_gn_ip == NULL) {
            validateSignature("arma::mat(*Z_gn_ip)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_Z_gn_ip = (Ptr_Z_gn_ip)R_GetCCallable("fort", "_fort_Z_gn_ip");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Z_gn_ip(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::vec T_fn_ip(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_T_fn_ip)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_T_fn_ip p_T_fn_ip = NULL;
        if (p_T_fn_ip == NULL) {
            validateSignature("arma::vec(*T_fn_ip)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_T_fn_ip = (Ptr_T_fn_ip)R_GetCCallable("fort", "_fort_T_fn_ip");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_T_fn_ip(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::mat T_gn_ip(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_T_gn_ip)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_T_gn_ip p_T_gn_ip = NULL;
        if (p_T_gn_ip == NULL) {
            validateSignature("arma::mat(*T_gn_ip)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_T_gn_ip = (Ptr_T_gn_ip)R_GetCCallable("fort", "_fort_T_gn_ip");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_T_gn_ip(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline double log_prior_pdf_ip4(const arma::vec& theta) {
        typedef SEXP(*Ptr_log_prior_pdf_ip4)(SEXP);
        static Ptr_log_prior_pdf_ip4 p_log_prior_pdf_ip4 = NULL;
        if (p_log_prior_pdf_ip4 == NULL) {
            validateSignature("double(*log_prior_pdf_ip4)(const arma::vec&)");
            p_log_prior_pdf_ip4 = (Ptr_log_prior_pdf_ip4)R_GetCCallable("fort", "_fort_log_prior_pdf_ip4");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_log_prior_pdf_ip4(Shield<SEXP>(Rcpp::wrap(theta)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double log_prior_pdf_ip3(const arma::vec& theta) {
        typedef SEXP(*Ptr_log_prior_pdf_ip3)(SEXP);
        static Ptr_log_prior_pdf_ip3 p_log_prior_pdf_ip3 = NULL;
        if (p_log_prior_pdf_ip3 == NULL) {
            validateSignature("double(*log_prior_pdf_ip3)(const arma::vec&)");
            p_log_prior_pdf_ip3 = (Ptr_log_prior_pdf_ip3)R_GetCCallable("fort", "_fort_log_prior_pdf_ip3");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_log_prior_pdf_ip3(Shield<SEXP>(Rcpp::wrap(theta)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double log_prior_pdf_ip2(const arma::vec& theta) {
        typedef SEXP(*Ptr_log_prior_pdf_ip2)(SEXP);
        static Ptr_log_prior_pdf_ip2 p_log_prior_pdf_ip2 = NULL;
        if (p_log_prior_pdf_ip2 == NULL) {
            validateSignature("double(*log_prior_pdf_ip2)(const arma::vec&)");
            p_log_prior_pdf_ip2 = (Ptr_log_prior_pdf_ip2)R_GetCCallable("fort", "_fort_log_prior_pdf_ip2");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_log_prior_pdf_ip2(Shield<SEXP>(Rcpp::wrap(theta)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double log_prior_pdf_ip1(const arma::vec& theta) {
        typedef SEXP(*Ptr_log_prior_pdf_ip1)(SEXP);
        static Ptr_log_prior_pdf_ip1 p_log_prior_pdf_ip1 = NULL;
        if (p_log_prior_pdf_ip1 == NULL) {
            validateSignature("double(*log_prior_pdf_ip1)(const arma::vec&)");
            p_log_prior_pdf_ip1 = (Ptr_log_prior_pdf_ip1)R_GetCCallable("fort", "_fort_log_prior_pdf_ip1");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_log_prior_pdf_ip1(Shield<SEXP>(Rcpp::wrap(theta)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double log_prior_pdf_ip0(const arma::vec& theta) {
        typedef SEXP(*Ptr_log_prior_pdf_ip0)(SEXP);
        static Ptr_log_prior_pdf_ip0 p_log_prior_pdf_ip0 = NULL;
        if (p_log_prior_pdf_ip0 == NULL) {
            validateSignature("double(*log_prior_pdf_ip0)(const arma::vec&)");
            p_log_prior_pdf_ip0 = (Ptr_log_prior_pdf_ip0)R_GetCCallable("fort", "_fort_log_prior_pdf_ip0");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_log_prior_pdf_ip0(Shield<SEXP>(Rcpp::wrap(theta)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double log_prior_pdf_ipn1(const arma::vec& theta) {
        typedef SEXP(*Ptr_log_prior_pdf_ipn1)(SEXP);
        static Ptr_log_prior_pdf_ipn1 p_log_prior_pdf_ipn1 = NULL;
        if (p_log_prior_pdf_ipn1 == NULL) {
            validateSignature("double(*log_prior_pdf_ipn1)(const arma::vec&)");
            p_log_prior_pdf_ipn1 = (Ptr_log_prior_pdf_ipn1)R_GetCCallable("fort", "_fort_log_prior_pdf_ipn1");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_log_prior_pdf_ipn1(Shield<SEXP>(Rcpp::wrap(theta)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double log_prior_pdf_ipn2(const arma::vec& theta) {
        typedef SEXP(*Ptr_log_prior_pdf_ipn2)(SEXP);
        static Ptr_log_prior_pdf_ipn2 p_log_prior_pdf_ipn2 = NULL;
        if (p_log_prior_pdf_ipn2 == NULL) {
            validateSignature("double(*log_prior_pdf_ipn2)(const arma::vec&)");
            p_log_prior_pdf_ipn2 = (Ptr_log_prior_pdf_ipn2)R_GetCCallable("fort", "_fort_log_prior_pdf_ipn2");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_log_prior_pdf_ipn2(Shield<SEXP>(Rcpp::wrap(theta)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double log_prior_pdf_ipn3(const arma::vec& theta) {
        typedef SEXP(*Ptr_log_prior_pdf_ipn3)(SEXP);
        static Ptr_log_prior_pdf_ipn3 p_log_prior_pdf_ipn3 = NULL;
        if (p_log_prior_pdf_ipn3 == NULL) {
            validateSignature("double(*log_prior_pdf_ipn3)(const arma::vec&)");
            p_log_prior_pdf_ipn3 = (Ptr_log_prior_pdf_ipn3)R_GetCCallable("fort", "_fort_log_prior_pdf_ipn3");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_log_prior_pdf_ipn3(Shield<SEXP>(Rcpp::wrap(theta)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double log_prior_pdf_ipn4(const arma::vec& theta) {
        typedef SEXP(*Ptr_log_prior_pdf_ipn4)(SEXP);
        static Ptr_log_prior_pdf_ipn4 p_log_prior_pdf_ipn4 = NULL;
        if (p_log_prior_pdf_ipn4 == NULL) {
            validateSignature("double(*log_prior_pdf_ipn4)(const arma::vec&)");
            p_log_prior_pdf_ipn4 = (Ptr_log_prior_pdf_ipn4)R_GetCCallable("fort", "_fort_log_prior_pdf_ipn4");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_log_prior_pdf_ipn4(Shield<SEXP>(Rcpp::wrap(theta)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline Rcpp::List create_xptrs_ip_all() {
        typedef SEXP(*Ptr_create_xptrs_ip_all)();
        static Ptr_create_xptrs_ip_all p_create_xptrs_ip_all = NULL;
        if (p_create_xptrs_ip_all == NULL) {
            validateSignature("Rcpp::List(*create_xptrs_ip_all)()");
            p_create_xptrs_ip_all = (Ptr_create_xptrs_ip_all)R_GetCCallable("fort", "_fort_create_xptrs_ip_all");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_create_xptrs_ip_all();
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

    inline double logsumexp(double logA, double logB) {
        typedef SEXP(*Ptr_logsumexp)(SEXP,SEXP);
        static Ptr_logsumexp p_logsumexp = NULL;
        if (p_logsumexp == NULL) {
            validateSignature("double(*logsumexp)(double,double)");
            p_logsumexp = (Ptr_logsumexp)R_GetCCallable("fort", "_fort_logsumexp");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_logsumexp(Shield<SEXP>(Rcpp::wrap(logA)), Shield<SEXP>(Rcpp::wrap(logB)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline arma::vec a1_fn_ipH(const arma::vec& theta, const arma::vec& known_params) {
        typedef SEXP(*Ptr_a1_fn_ipH)(SEXP,SEXP);
        static Ptr_a1_fn_ipH p_a1_fn_ipH = NULL;
        if (p_a1_fn_ipH == NULL) {
            validateSignature("arma::vec(*a1_fn_ipH)(const arma::vec&,const arma::vec&)");
            p_a1_fn_ipH = (Ptr_a1_fn_ipH)R_GetCCallable("fort", "_fort_a1_fn_ipH");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_a1_fn_ipH(Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::mat P1_fn_ipH(const arma::vec& theta, const arma::vec& known_params) {
        typedef SEXP(*Ptr_P1_fn_ipH)(SEXP,SEXP);
        static Ptr_P1_fn_ipH p_P1_fn_ipH = NULL;
        if (p_P1_fn_ipH == NULL) {
            validateSignature("arma::mat(*P1_fn_ipH)(const arma::vec&,const arma::vec&)");
            p_P1_fn_ipH = (Ptr_P1_fn_ipH)R_GetCCallable("fort", "_fort_P1_fn_ipH");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_P1_fn_ipH(Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::mat R_fn_ipH(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_R_fn_ipH)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_R_fn_ipH p_R_fn_ipH = NULL;
        if (p_R_fn_ipH == NULL) {
            validateSignature("arma::mat(*R_fn_ipH)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_R_fn_ipH = (Ptr_R_fn_ipH)R_GetCCallable("fort", "_fort_R_fn_ipH");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_R_fn_ipH(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::vec T_fn_ipH(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_T_fn_ipH)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_T_fn_ipH p_T_fn_ipH = NULL;
        if (p_T_fn_ipH == NULL) {
            validateSignature("arma::vec(*T_fn_ipH)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_T_fn_ipH = (Ptr_T_fn_ipH)R_GetCCallable("fort", "_fort_T_fn_ipH");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_T_fn_ipH(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::mat T_gn_ipH(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_T_gn_ipH)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_T_gn_ipH p_T_gn_ipH = NULL;
        if (p_T_gn_ipH == NULL) {
            validateSignature("arma::mat(*T_gn_ipH)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_T_gn_ipH = (Ptr_T_gn_ipH)R_GetCCallable("fort", "_fort_T_gn_ipH");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_T_gn_ipH(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline Rcpp::List create_xptrs_H_all() {
        typedef SEXP(*Ptr_create_xptrs_H_all)();
        static Ptr_create_xptrs_H_all p_create_xptrs_H_all = NULL;
        if (p_create_xptrs_H_all == NULL) {
            validateSignature("Rcpp::List(*create_xptrs_H_all)()");
            p_create_xptrs_H_all = (Ptr_create_xptrs_H_all)R_GetCCallable("fort", "_fort_create_xptrs_H_all");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_create_xptrs_H_all();
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

    inline arma::vec a1_fn(const arma::vec& theta, const arma::vec& known_params) {
        typedef SEXP(*Ptr_a1_fn)(SEXP,SEXP);
        static Ptr_a1_fn p_a1_fn = NULL;
        if (p_a1_fn == NULL) {
            validateSignature("arma::vec(*a1_fn)(const arma::vec&,const arma::vec&)");
            p_a1_fn = (Ptr_a1_fn)R_GetCCallable("fort", "_fort_a1_fn");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_a1_fn(Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::mat P1_fn(const arma::vec& theta, const arma::vec& known_params) {
        typedef SEXP(*Ptr_P1_fn)(SEXP,SEXP);
        static Ptr_P1_fn p_P1_fn = NULL;
        if (p_P1_fn == NULL) {
            validateSignature("arma::mat(*P1_fn)(const arma::vec&,const arma::vec&)");
            p_P1_fn = (Ptr_P1_fn)R_GetCCallable("fort", "_fort_P1_fn");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_P1_fn(Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::mat H_fn(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_H_fn)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_H_fn p_H_fn = NULL;
        if (p_H_fn == NULL) {
            validateSignature("arma::mat(*H_fn)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_H_fn = (Ptr_H_fn)R_GetCCallable("fort", "_fort_H_fn");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_H_fn(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::mat R_fn(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_R_fn)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_R_fn p_R_fn = NULL;
        if (p_R_fn == NULL) {
            validateSignature("arma::mat(*R_fn)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_R_fn = (Ptr_R_fn)R_GetCCallable("fort", "_fort_R_fn");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_R_fn(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::vec Z_fn(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_Z_fn)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_Z_fn p_Z_fn = NULL;
        if (p_Z_fn == NULL) {
            validateSignature("arma::vec(*Z_fn)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_Z_fn = (Ptr_Z_fn)R_GetCCallable("fort", "_fort_Z_fn");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Z_fn(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::mat Z_gn(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_Z_gn)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_Z_gn p_Z_gn = NULL;
        if (p_Z_gn == NULL) {
            validateSignature("arma::mat(*Z_gn)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_Z_gn = (Ptr_Z_gn)R_GetCCallable("fort", "_fort_Z_gn");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Z_gn(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::vec T_fn(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_T_fn)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_T_fn p_T_fn = NULL;
        if (p_T_fn == NULL) {
            validateSignature("arma::vec(*T_fn)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_T_fn = (Ptr_T_fn)R_GetCCallable("fort", "_fort_T_fn");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_T_fn(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::mat T_gn(const unsigned int t, const arma::vec& alpha, const arma::vec& theta, const arma::vec& known_params, const arma::mat& known_tv_params) {
        typedef SEXP(*Ptr_T_gn)(SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_T_gn p_T_gn = NULL;
        if (p_T_gn == NULL) {
            validateSignature("arma::mat(*T_gn)(const unsigned int,const arma::vec&,const arma::vec&,const arma::vec&,const arma::mat&)");
            p_T_gn = (Ptr_T_gn)R_GetCCallable("fort", "_fort_T_gn");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_T_gn(Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(theta)), Shield<SEXP>(Rcpp::wrap(known_params)), Shield<SEXP>(Rcpp::wrap(known_tv_params)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline double log_prior_pdf(const arma::vec& theta) {
        typedef SEXP(*Ptr_log_prior_pdf)(SEXP);
        static Ptr_log_prior_pdf p_log_prior_pdf = NULL;
        if (p_log_prior_pdf == NULL) {
            validateSignature("double(*log_prior_pdf)(const arma::vec&)");
            p_log_prior_pdf = (Ptr_log_prior_pdf)R_GetCCallable("fort", "_fort_log_prior_pdf");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_log_prior_pdf(Shield<SEXP>(Rcpp::wrap(theta)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline Rcpp::List create_xptrs() {
        typedef SEXP(*Ptr_create_xptrs)();
        static Ptr_create_xptrs p_create_xptrs = NULL;
        if (p_create_xptrs == NULL) {
            validateSignature("Rcpp::List(*create_xptrs)()");
            p_create_xptrs = (Ptr_create_xptrs)R_GetCCallable("fort", "_fort_create_xptrs");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_create_xptrs();
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

}

#endif // RCPP_fort_RCPPEXPORTS_H_GEN_
