# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

a1_fn_ip <- function(theta, known_params) {
    .Call(`_fort_a1_fn_ip`, theta, known_params)
}

P1_fn_ip <- function(theta, known_params) {
    .Call(`_fort_P1_fn_ip`, theta, known_params)
}

H_fn_ip <- function(t, alpha, theta, known_params, known_tv_params) {
    .Call(`_fort_H_fn_ip`, t, alpha, theta, known_params, known_tv_params)
}

R_fn_ip <- function(t, alpha, theta, known_params, known_tv_params) {
    .Call(`_fort_R_fn_ip`, t, alpha, theta, known_params, known_tv_params)
}

Z_fn_ip <- function(t, alpha, theta, known_params, known_tv_params) {
    .Call(`_fort_Z_fn_ip`, t, alpha, theta, known_params, known_tv_params)
}

Z_gn_ip <- function(t, alpha, theta, known_params, known_tv_params) {
    .Call(`_fort_Z_gn_ip`, t, alpha, theta, known_params, known_tv_params)
}

T_fn_ip <- function(t, alpha, theta, known_params, known_tv_params) {
    .Call(`_fort_T_fn_ip`, t, alpha, theta, known_params, known_tv_params)
}

T_gn_ip <- function(t, alpha, theta, known_params, known_tv_params) {
    .Call(`_fort_T_gn_ip`, t, alpha, theta, known_params, known_tv_params)
}

log_prior_pdf_ip4 <- function(theta) {
    .Call(`_fort_log_prior_pdf_ip4`, theta)
}

log_prior_pdf_ip3 <- function(theta) {
    .Call(`_fort_log_prior_pdf_ip3`, theta)
}

log_prior_pdf_ip2 <- function(theta) {
    .Call(`_fort_log_prior_pdf_ip2`, theta)
}

log_prior_pdf_ip1 <- function(theta) {
    .Call(`_fort_log_prior_pdf_ip1`, theta)
}

log_prior_pdf_ip0 <- function(theta) {
    .Call(`_fort_log_prior_pdf_ip0`, theta)
}

log_prior_pdf_ipn1 <- function(theta) {
    .Call(`_fort_log_prior_pdf_ipn1`, theta)
}

log_prior_pdf_ipn2 <- function(theta) {
    .Call(`_fort_log_prior_pdf_ipn2`, theta)
}

log_prior_pdf_ipn3 <- function(theta) {
    .Call(`_fort_log_prior_pdf_ipn3`, theta)
}

log_prior_pdf_ipn4 <- function(theta) {
    .Call(`_fort_log_prior_pdf_ipn4`, theta)
}

create_xptrs_ip_all <- function() {
    .Call(`_fort_create_xptrs_ip_all`)
}

a1_fn <- function(theta, known_params) {
    .Call(`_fort_a1_fn`, theta, known_params)
}

P1_fn <- function(theta, known_params) {
    .Call(`_fort_P1_fn`, theta, known_params)
}

H_fn <- function(t, alpha, theta, known_params, known_tv_params) {
    .Call(`_fort_H_fn`, t, alpha, theta, known_params, known_tv_params)
}

R_fn <- function(t, alpha, theta, known_params, known_tv_params) {
    .Call(`_fort_R_fn`, t, alpha, theta, known_params, known_tv_params)
}

Z_fn <- function(t, alpha, theta, known_params, known_tv_params) {
    .Call(`_fort_Z_fn`, t, alpha, theta, known_params, known_tv_params)
}

Z_gn <- function(t, alpha, theta, known_params, known_tv_params) {
    .Call(`_fort_Z_gn`, t, alpha, theta, known_params, known_tv_params)
}

T_fn <- function(t, alpha, theta, known_params, known_tv_params) {
    .Call(`_fort_T_fn`, t, alpha, theta, known_params, known_tv_params)
}

T_gn <- function(t, alpha, theta, known_params, known_tv_params) {
    .Call(`_fort_T_gn`, t, alpha, theta, known_params, known_tv_params)
}

log_prior_pdf <- function(theta) {
    .Call(`_fort_log_prior_pdf`, theta)
}

create_xptrs <- function() {
    .Call(`_fort_create_xptrs`)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_fort_RcppExport_registerCCallable`)
})
